/**
 * lie_idle.js
 * PILLAR 3: ASCETICISM AS FOCUS (Passive Gameplay)
 *
 * Manages the passive accumulation and decay of 'Lie' currency.
 * "Lies" are a resource generated by doing nothing, or by specific
 * idle structures (accelerators).
 */

import { System } from '../ecs.js';

export class LieIdleSystem extends System {
    constructor() {
        super();
        // Requires entities that can generate or hold Lies.
        // Typically this might just be the Player entity, or specific structures.
        this.requiredComponents = ['LieComponent'];
    }

    update(world, entities, turns_passed) {
        if (turns_passed <= 0) return;

        for (const entityId of entities) {
            const lieData = world.getComponent(entityId, 'LieComponent');

            // 1. CALCULATE GENERATION
            // Base generation + any accelerators (e.g., from traits or nearby objects)
            // For now, we assume standard base rate if accelerator is missing.
            const generationRate = lieData.baseGeneration + (lieData.acceleratorBonus || 0);
            const grossGenerated = generationRate * turns_passed;

            // 2. CALCULATE DECAY
            // "It slowly disappears" - GDD Pillar 3.
            // Decay might be a flat rate or a percentage of current total.
            // Using percentage here for "radioactive decay" feel: more lies = faster decay.
            const decayAmount = (lieData.currentAmount * lieData.decayRate) * turns_passed;

            // 3. APPLY NET CHANGE
            lieData.currentAmount += grossGenerated - decayAmount;

            // Ensure it doesn't drop below zero
            if (lieData.currentAmount < 0) {
                lieData.currentAmount = 0;
            }

            // Optional: Cap at a maximum if defined
            if (lieData.maxAmount && lieData.currentAmount > lieData.maxAmount) {
                lieData.currentAmount = lieData.maxAmount;
            }

            // Debug log for now, since there's no UI for it yet
            // console.log(`Entity ${entityId} Lies: ${lieData.currentAmount.toFixed(2)} (+${grossGenerated.toFixed(2)} / -${decayAmount.toFixed(2)})`);
        }
    }
}
